### ISSUE TITLE
Monitoring Module, "PERMISSION_DENIED: The caller does not have permission" error.

### ISSUE THREAD

**Issue by rui-gao** [curioswitch/curiostack#146]
Tried to enable monitoring module of curiostack in local merchine, but get `PERMISSION_DENIED: The caller does not have permission`.

## Error
```
[WARN ] 2018-06-11 16:57:40.436 [Thread-8] curioswitch.common.server.framework.monitoring.StackdriverReporter - Error reporting traces.
com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:55) ~[gax-1.23.0.jar:1.23.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-1.23.0.jar:1.23.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-1.23.0.jar:1.23.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95) [gax-grpc-1.23.0.jar:1.23.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61) [api-common-1.5.0.jar:?]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341) [guava-24.1-jre.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) [guava-24.1-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027) [guava-24.1-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:868) [guava-24.1-jre.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:713) [guava-24.1-jre.jar:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:492) [grpc-stub-1.11.0.jar:1.11.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467) [grpc-stub-1.11.0.jar:1.11.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.11.0.jar:1.11.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.11.0.jar:1.11.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: io.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.11.0.jar:1.11.0]
	... 22 more
```

## Config
```
gcloud {
  serviceAccountBase64: "Service account(with roles: Cloud Trace Agent, Logs Writer,Monitoring Editor) key json file, base64 encoded"
  credentialScopes: ["https://www.googleapis.com/auth/logging.write", "https://www.googleapis.com/auth/monitoring.write", "https://www.googleapis.com/auth/trace.append"]
}

monitoring {
  serverName: my-server-local
  stackdriverProjectId: 'my-server-stackdrive-project-id'
  reportTraces: true
  traceReportInterval: 5s
  traceQueueSize: 10000
}
```

Should I add more roles other than `Cloud Trace Agent, Logs Writer,Monitoring Editor` to the service account? Or need to add more credential scopes into gcloud section of the config file?

**Comment by chokoswitch** [comment]
Currently the stackdriver reporting does not use `armeria-gcloud` here, it uses the standard `google-cloud-java` upstream client library. This means it only authenticates using Google Application Default credentials - you can probably fix the issue on local machine by making sure to login with `gcloud auth application-default login` with an account that has the necessary permissions to write traces.

After next armeria version is released with https://github.com/line/armeria/pull/1245 included, I will switch the reporting to use `armeria-gcloud`, which will use the service account / scopes you have defined there.

**Comment by demongaorui** [comment]
```
 $ gcloud auth application-default login
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?redirect_uri=******


Credentials saved to file: [/Users/Rui/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests
Application Default Credentials.

To generate an access token for other uses, run:
  gcloud auth application-default print-access-token

```

Ran `gcloud auth application-default login` and finished the auth in the popup webpage. But, still get the same error.

BTW, the server is running based on `org.curioswitch.curiostack:gradle-curiostack-plugin:0.0.135`, guessing upgrade curiostack version may could hlep, so tried upgrade, but get `SunJSSE selected, but Jetty NPN/ALPN unavailable` error when try to run server with curiostack 0.0.142. Any ideas?

**Comment by chokoswitch** [comment]
Sorry for the late response. I'm not sure why on `0.0.135`, logging in with `gcloud` wouldn't fix it. I can only think that you logged-in with an account that doesn't have permission for trace on your project (perhaps you accidentally logged in with a personal instead of work account?). You can also try to use `activate-service-account`

At `0.0.146`, curiostack should respect the `gcloud` configuration in `application.conf` for trace too as it uses `armeria-google-cloud-trace`. I haven't seen the error you get with `142` though, it would only happen on Java 8 without a working `netty-tcnative-boringssl-static`. But I guess you're using Java 10, so it should either use `boringssl` or java 10 but has no reason to fail with an NPN error...

**Comment by demongaorui** [comment]
Thanks for replying! I'm sure that the account was right. And just updated to 0.0.153 now, will try the `gcloud` configuration in application.conf to see whether it works in 0.0.153.

**Comment by demongaorui** [comment]
BTW, for `credentialScopes` , do you have a recommended necessary sope list?
```
gcloud {
  serviceAccountBase64: ""
  credentialScopes: []
}
```

**Comment by demongaorui** [comment]
Seems the server is using the credentials from Cloud SDK instead of service account in `gcloud ` configuration. Seems need other config to make service account as higher priority than Cloud SDK?

### Config
```
gcloud {
  serviceAccountBase64: "Service accoun key json file, base64 encoded"
  credentialScopes: ["https://www.googleapis.com/auth/logging.write", "https://www.googleapis.com/auth/logging.admin", "https://www.googleapis.com/auth/monitoring.admin", "https://www.googleapis.com/auth/trace.append"]
}

monitoring {
  serverName: my-server-local
  stackdriverProjectId: 'my-server-stackdrive-project-id'
  reportTraces: true
  traceReportInterval: 5s
  traceQueueSize: 10000
}
```

### Error message
```
Jul 26, 2018 7:06:04 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
[WARN ] 2018-07-26 19:06:05.840 [armeria-common-worker-nio-2-6] curioswitch.common.server.framework.monitoring.StackdriverReporter - Error reporting traces.
io.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.13.2.jar:1.13.2]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:468) [grpc-stub-1.13.2.jar:1.13.2]
	at com.linecorp.armeria.client.grpc.ArmeriaClientCall.close(ArmeriaClientCall.java:293) [armeria-grpc-0.67.2.jar:?]
```

**Comment by chokoswitch** [comment]
Ah also, the auth settings were moved into a subobject, so `gcloud.auth`

https://github.com/curioswitch/curiostack/blob/master/common/google-cloud/core/src/main/resources/reference.conf

Also, the framework sets a default scope here

https://github.com/curioswitch/curiostack/blob/master/common/server/framework/src/main/resources/curio-server-framework-nonlocal.conf#L41

Scopes are an old, sort of deprecated concept and are hard to reason about due to IAM roles having the same functionality, so I recommend using `cloud-platform` scope and controlling permissions using IAM instead.
