### ISSUE TITLE
Armeria integration failed

### ISSUE THREAD

**Issue by rolandblain** [curioswitch/curiostack#601]
```
Caused by: java.lang.IllegalStateException: Could not generate marshaller, this is generally a bug in this library. Please file a report at https://github.com/curioswitch/curiostack with this stack trace and an example proto to reproduce.
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildOrFindMarshaller(TypeSpecificMarshaller.java:284)
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildAndAdd(TypeSpecificMarshaller.java:160)
	at org.curioswitch.common.protobuf.json.MessageMarshaller$Builder.build(MessageMarshaller.java:425)
	at com.linecorp.armeria.common.grpc.GrpcJsonUtil.jsonMarshaller(GrpcJsonUtil.java:62)
	at com.linecorp.armeria.common.grpc.GrpcJsonMarshallerBuilder.build(GrpcJsonMarshallerBuilder.java:71)
	at com.linecorp.armeria.common.grpc.GrpcJsonMarshaller.of(GrpcJsonMarshaller.java:45)
	at com.linecorp.armeria.server.grpc.GrpcServiceBuilder$$Lambda$641/000000000000000000.apply(Unknown Source)
	at com.linecorp.armeria.internal.shaded.guava.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61)
	at com.linecorp.armeria.internal.shaded.guava.collect.CollectCollectors$$Lambda$627/000000000000000000.accept(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.linecorp.armeria.server.grpc.FramedGrpcService.<init>(FramedGrpcService.java:127)
	at com.linecorp.armeria.server.grpc.GrpcServiceBuilder.build(GrpcServiceBuilder.java:479)
	at com.myapp.core.config.ArmeriaServerConfiguration$armeriaServerConfigurator$1.configure(ArmeriaServerConfiguration.kt:29)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.lambda$getWebServer$3(ArmeriaReactiveWebServerFactory.java:206)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory$$Lambda$635/000000000000000000.accept(Unknown Source)
	at com.linecorp.armeria.internal.shaded.guava.collect.ImmutableList.forEach(ImmutableList.java:405)
	at com.linecorp.armeria.spring.web.reactive.ArmeriaReactiveWebServerFactory.getWebServer(ArmeriaReactiveWebServerFactory.java:206)
	at org.springframework.boot.web.reactive.context.WebServerManager.<init>(WebServerManager.java:49)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:90)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:77)
	... 13 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.curioswitch.common.protobuf.json.TypeSpecificMarshaller$ByteBuddy$zhONG0fu.<init>(com.myapp.protobuf.StockPriceRequest)
	at java.lang.Class.newNoSuchMethodException(Class.java:567)
	at java.lang.Class.getConstructor(Class.java:609)
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildOrFindMarshaller(TypeSpecificMarshaller.java:278)
	... 40 common frames omitted
```

details:
https://github.com/line/armeria/issues/3176

**Comment by probepark** [comment]
Try to disable spring-boot-devtools dependency

**Comment by rolandblain** [comment]
@probepark It works! thank you I'll buy you a coffee
