### ISSUE TITLE
Brand new `optional` in proto3 does not work with `protobuf-jackson`

### ISSUE THREAD

**Issue by ikhoon** [curioswitch/curiostack#628]
`optional` fields are experimentally revived in Protobuf 3.12. https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md
Protobuf 3.15 enables `optional` fields by default. https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0
However, `protobuf-jackson` seems not to support an `optional` field with proto3. I got reported the following message from a LINE internal user.
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'armeriaServer' defined in class path resource [com/linecorp/armeria/spring/ArmeriaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.lang.IllegalStateException: Could not find oneof case method.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.2.jar:2.4.2]
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:13) ~[main/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.linecorp.armeria.server.Server]: Factory method 'armeriaServer' threw exception; nested exception is java.lang.IllegalStateException: Could not find oneof case method.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.3.jar:5.3.3]
	... 20 common frames omitted
Caused by: java.lang.IllegalStateException: Could not find oneof case method.
	at org.curioswitch.common.protobuf.json.DoParse.apply(DoParse.java:393) ~[protobuf-jackson-1.2.0.jar:na]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:708) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:693) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:600) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5751) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3659) ~[byte-buddy-1.10.19.jar:na]
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3897) ~[byte-buddy-1.10.19.jar:na]
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildOrFindMarshaller(TypeSpecificMarshaller.java:275) ~[protobuf-jackson-1.2.0.jar:na]
	at org.curioswitch.common.protobuf.json.TypeSpecificMarshaller.buildAndAdd(TypeSpecificMarshaller.java:158) ~[protobuf-jackson-1.2.0.jar:na]
	at org.curioswitch.common.protobuf.json.MessageMarshaller$Builder.build(MessageMarshaller.java:425) ~[protobuf-jackson-1.2.0.jar:na]
	at com.linecorp.armeria.common.grpc.GrpcJsonUtil.jsonMarshaller(GrpcJsonUtil.java:62) ~[armeria-grpc-1.9.2.jar:na]
	at com.linecorp.armeria.common.grpc.GrpcJsonMarshallerBuilder.build(GrpcJsonMarshallerBuilder.java:71) ~[armeria-grpc-1.9.2.jar:na]
	at com.linecorp.armeria.common.grpc.GrpcJsonMarshaller.of(GrpcJsonMarshaller.java:45) ~[armeria-grpc-1.9.2.jar:na]
	at com.linecorp.armeria.internal.shaded.guava.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:182) ~[armeria-1.9.2.jar:na]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4820) ~[na:na]
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4828) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.linecorp.armeria.server.grpc.FramedGrpcService.<init>(FramedGrpcService.java:129) ~[armeria-grpc-1.9.2.jar:na]
	at com.linecorp.armeria.server.grpc.GrpcServiceBuilder.build(GrpcServiceBuilder.java:616) ~[armeria-grpc-1.9.2.jar:na]
	at com.example.demo.ArmeriaConfig$armeriaServiceInitializer$1.configure(ArmeriaConfig.kt:49) ~[main/:na]
	at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.lambda$configureServerWithArmeriaSettings$0(ArmeriaConfigurationUtil.java:118) ~[armeria-spring-boot2-autoconfigure-1.9.2.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.linecorp.armeria.internal.spring.ArmeriaConfigurationUtil.configureServerWithArmeriaSettings(ArmeriaConfigurationUtil.java:118) ~[armeria-spring-boot2-autoconfigure-1.9.2.jar:na]
	at com.linecorp.armeria.spring.AbstractArmeriaAutoConfiguration.armeriaServer(AbstractArmeriaAutoConfiguration.java:91) ~[armeria-spring-boot2-autoconfigure-1.9.2.jar:na]
	at com.linecorp.armeria.spring.ArmeriaAutoConfiguration$$EnhancerBySpringCGLIB$$fae8b383.CGLIB$armeriaServer$0(<generated>) ~[armeria-spring-boot2-autoconfigure-1.9.2.jar:na]
	at com.linecorp.armeria.spring.ArmeriaAutoConfiguration$$EnhancerBySpringCGLIB$$fae8b383$$FastClassBySpringCGLIB$$149d545c.invoke(<generated>) ~[armeria-spring-boot2-autoconfigure-1.9.2.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.3.jar:5.3.3]
	at com.linecorp.armeria.spring.ArmeriaAutoConfiguration$$EnhancerBySpringCGLIB$$fae8b383.armeriaServer(<generated>) ~[armeria-spring-boot2-autoconfigure-1.9.2.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.3.jar:5.3.3]
	... 21 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.example.grpc.hello.HelloRequest$Builder.getOptionalNameCase()
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2633) ~[na:na]
	at org.curioswitch.common.protobuf.json.DoParse.apply(DoParse.java:388) ~[protobuf-jackson-1.2.0.jar:na]
	... 64 common frames omitted
Process finished with exit code 1
```
It would be awesome to support optional fields with `protobuf-jackson`.

**Comment by ikhoon** [comment]
@anuraaga Do you have time to take a look at this issue?

**Comment by chokoswitch** [comment]
Sure will check it out. Seems like the reflection backwards compatibility hack isn't quite complete

**Comment by vh** [comment]
Hey @chokoswitch. Having the same issue. Did you get a chance to look into this? Thanks!

**Comment by chokoswitch** [comment]
Sorry for the huge delay on this. Expecting to get to this over the
holidays.
